version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: memcached

    mariadb:
      image: mariadb:10.1
      container_name: mariadb
      working_dir: /app
      volumes:
        - ./Projects/Api:/app
      environment:
        - MYSQL_ROOT_PASSWORD=docker
        - MYSQL_DATABASE=test
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
      ports:
        - "8001:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mariadb
        - PMA_PORT=3306
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
        - MYSQL_ROOT_PASSWORD=docker
      restart: always
      ports:
          - 8002:80
      volumes:
          - /app
      links:
          - mariadb

    app:
      image: nginx:alpine
      container_name: app
      working_dir: /app
      volumes:
          - ./Projects/App:/app
          - ./Docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      ports:
          - "8010:8080"

    php-fpm-app:
      build: Docker/php-fpm-app
      container_name: php-fpm-app
      working_dir: /app
      volumes:
          - ./Projects/App:/app
          - ./Docker/php-fpm-app/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


